### ISSUE TITLE
关于CascadeType.MERGE的疑问

### ISSUE THREAD

**Issue by FANE-Tang** [zempty-zhaoxuan/spring-data-jpa#1]
你好，测试发现，当Student对Desk的@OneToOne级联属性为none时，更改Student的Desk的属性，save Student时，Desk依然会一并更新，这是为什么呢？是save时对于级联有默认的传播行为，还是CascadeType.MERGE有别的功能？

**Comment by zempty-zhaoxuan** [comment]
student 里面有个 desk ，更改了这个属性值，保存的时候，如果 jpa 框架不去更新，那么应该怎么操作呢？
1. 如果这个属性不是实体类属性 desk ，就是一个普通的属性，这应该很好理解，改变了，就应该更新
2. 现在属性是desk ，是一个实体类属性，修改了，就不去处理了？ 没必要区别对待，正常更新而已！

这里虽然更新了，但是是一个**有问题的更新**： 比如我在文中的这个例子 student 和 desk  是 OnetoOne 的一个关系，这里维护了一个第三张表：stu_desk ,  虽然你修改了 desk 的值，但是这张表的关系并没有维护进来，这个更新是失败的，并没有做到级联更新（CascadeType.MERGE）， **级联更新是不仅要更新修改的值，更是要更新彼此之间的一个关系**，否则是不构成级联的，这里在工作当中应该注意一下，否则可能要出问题的。

关于级联的一个操作，应该熟悉一下文中提到的几个级联操作，建议花点时间去研究一下，操作一下，搞明白了，工作起来才回事半功倍：

cascade表示关联关系中的级联操作权限，有如下权限：

CascadeType.PERSIST 该级联是级联保存。
CascadeType.MERGE 该级联是级联更新
CascadeType.REMOVE 该级联是级联删除
CascadeType.REFRESH 该级联是级联刷新(不常用）
CascadeType.DETACH 该级联是级联托管（不常用）
CascadeType.ALL 具有上述五个级联的功能

PERSIST 对应级联保存， MERGE 对应级联更新，REMOVE 对应级联删除，ALL 具有以上所有功能，常用的也就这 4 个。

综上：针对你上述的问题，你如过需要修改 desk 的属性值，正确的做法就应该是用级联（CascadeType.MERGE），因为它们之间存在着级联关系，否则，彼此之间的关系维护不进来。

**Comment by FANE-Tang** [comment]
明白了，多谢回复！
